"""AI document generation service.

Defines `DocumentGenerationService` as the interface the rest of the app
depends on, and `GeminiDocumentGenerationService` as the current
implementation (Gemini API free tier, called via plain HTTP — no SDK
dependency). Swapping providers means writing a new class satisfying the
same interface.
"""

from __future__ import annotations

from dataclasses import dataclass

import httpx

from app.core.config import Settings
from app.core.logging import get_logger

logger = get_logger(__name__)

_GEMINI_ENDPOINT_TEMPLATE = (
    "https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent"
)

_SECTION_MARKERS = {
    "documentation": "===DOCUMENTATION===",
    "sop": "===SOP===",
    "faq": "===FAQ===",
    "summary": "===SUMMARY===",
}

_PROMPT_TEMPLATE = """You are a technical writer. Below is a transcript of a screen \
recording of someone using a piece of software. Based ONLY on this transcript, \
produce four sections, each written as Markdown.

- documentation: end-user documentation describing what the software does and \
how to use the workflow shown.
- sop: a numbered Standard Operating Procedure (step-by-step instructions) for \
reproducing the workflow shown.
- faq: 3-5 likely questions a new user would ask about this workflow, each with \
a concise answer, as a Markdown list.
- summary: a 2-3 sentence plain-English summary of what happens in the recording.

Transcript:
\"\"\"
{transcript}
\"\"\"

Respond with EXACTLY this format and nothing else — no preamble, no closing \
remarks. Each marker must appear on its own line, exactly as written (including \
the "===" on both sides), followed by that section's Markdown content:

===DOCUMENTATION===
<documentation content here>
===SOP===
<sop content here>
===FAQ===
<faq content here>
===SUMMARY===
<summary content here>"""


class DocumentGenerationError(Exception):
    """Raised when AI document generation fails or returns an unusable response."""


@dataclass(frozen=True, slots=True)
class GeneratedDocuments:
    documentation: str
    sop: str
    faq: str
    summary: str


class GeminiDocumentGenerationService:
    """Generates documentation/SOP/FAQ/summary from a transcript using the
    Gemini API free tier. Requires `GEMINI_API_KEY` to be set.

    Uses plain delimiter-separated sections rather than asking the model for
    JSON: free-form Markdown (quotes, newlines, code blocks) reliably breaks
    JSON string escaping when generated by an LLM — this was tried and hit
    three distinct JSON-parsing failures (trailing data, control characters,
    unescaped quotes) before switching to this approach, which has no
    escaping to get wrong in the first place.
    """

    def __init__(self, settings: Settings) -> None:
        self._settings = settings

    async def generate(self, transcript: str) -> GeneratedDocuments:
        if not self._settings.gemini_api_key:
            raise DocumentGenerationError(
                "GEMINI_API_KEY is not configured — set it in the environment/.env file."
            )

        url = _GEMINI_ENDPOINT_TEMPLATE.format(model=self._settings.gemini_model)
        prompt = _PROMPT_TEMPLATE.format(transcript=transcript)

        payload = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {"temperature": 0.3},
        }

        response = await self._post_with_retry(url, payload)
        return self._parse_response(response.json())

    async def _post_with_retry(self, url: str, payload: dict) -> httpx.Response:
        """POST to Gemini, retrying on 429 (rate limited) / 503 (overloaded)
        — both are common on the free tier under load and are expected to
        resolve on their own within seconds, per Google's own error message
        ("Spikes in demand are usually temporary"). Anything else (4xx
        auth/validation errors, other 5xx) fails immediately — retrying
        those would just waste time on an error that won't self-resolve.
        """
        import asyncio

        max_attempts = 3
        backoff_seconds = 2.0

        last_response: httpx.Response | None = None

        for attempt in range(1, max_attempts + 1):
            try:
                async with httpx.AsyncClient(timeout=self._settings.gemini_timeout) as client:
                    response = await client.post(
                        url,
                        params={"key": self._settings.gemini_api_key},
                        json=payload,
                    )
            except httpx.HTTPError as exc:
                raise DocumentGenerationError(f"Gemini API request failed: {exc}") from exc

            if response.status_code == 200:
                return response

            if response.status_code not in (429, 503) or attempt == max_attempts:
                raise DocumentGenerationError(
                    f"Gemini API returned {response.status_code}: {response.text[:500]}"
                )

            logger.warning(
                "gemini_transient_error_retrying",
                status_code=response.status_code,
                attempt=attempt,
                max_attempts=max_attempts,
            )
            last_response = response
            await asyncio.sleep(backoff_seconds * attempt)

        # Unreachable in practice (loop always returns or raises), but keeps
        # the type checker satisfied and fails safely if it ever is reached.
        assert last_response is not None
        raise DocumentGenerationError(
            f"Gemini API returned {last_response.status_code}: {last_response.text[:500]}"
        )

    def _parse_response(self, body: dict) -> GeneratedDocuments:
        try:
            candidates = body["candidates"]
            text = candidates[0]["content"]["parts"][0]["text"]
        except (KeyError, IndexError, TypeError) as exc:
            logger.error("gemini_response_unparsable", body=body)
            raise DocumentGenerationError(
                f"Gemini returned an unexpected response shape: {exc}"
            ) from exc

        sections = self._split_sections(text)

        missing = [key for key in _SECTION_MARKERS if key not in sections]
        if missing:
            logger.error("gemini_response_missing_sections", missing=missing, text=text[:1000])
            raise DocumentGenerationError(
                f"Gemini response was missing expected section(s): {', '.join(missing)}"
            )

        return GeneratedDocuments(
            documentation=sections["documentation"],
            sop=sections["sop"],
            faq=sections["faq"],
            summary=sections["summary"],
        )

    def _split_sections(self, text: str) -> dict[str, str]:
        """Split `text` on the `===SECTION===` markers, returning
        `{key: content}` for whichever markers are actually present. Robust
        to the model adding stray whitespace/preamble around markers (splits
        on the marker text itself, not on exact line boundaries)."""
        import re

        # Build a single regex that matches any marker, capturing which one.
        marker_pattern = "|".join(re.escape(marker) for marker in _SECTION_MARKERS.values())
        parts = re.split(f"({marker_pattern})", text)

        marker_to_key = {marker: key for key, marker in _SECTION_MARKERS.items()}
        sections: dict[str, str] = {}

        # re.split with a capturing group yields: [pre-text, marker, content, marker, content, ...]
        for i in range(1, len(parts) - 1, 2):
            marker = parts[i].strip()
            content = parts[i + 1].strip()
            key = marker_to_key.get(marker)
            if key:
                sections[key] = content

        return sections